//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.PKServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PKServiceReference.Iannounce")]
    public interface Iannounce {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iannounce/GetXMLData", ReplyAction="http://tempuri.org/Iannounce/GetXMLDataResponse")]
        string GetXMLData(string SupID, string AplyDate, string CreDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iannounce/GetXMLData", ReplyAction="http://tempuri.org/Iannounce/GetXMLDataResponse")]
        System.Threading.Tasks.Task<string> GetXMLDataAsync(string SupID, string AplyDate, string CreDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IannounceChannel : WindowsFormsApplication1.PKServiceReference.Iannounce, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IannounceClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.PKServiceReference.Iannounce>, WindowsFormsApplication1.PKServiceReference.Iannounce {
        
        public IannounceClient() {
        }
        
        public IannounceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IannounceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IannounceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IannounceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetXMLData(string SupID, string AplyDate, string CreDate) {
            return base.Channel.GetXMLData(SupID, AplyDate, CreDate);
        }
        
        public System.Threading.Tasks.Task<string> GetXMLDataAsync(string SupID, string AplyDate, string CreDate) {
            return base.Channel.GetXMLDataAsync(SupID, AplyDate, CreDate);
        }
    }
}
